### PR TITLE
refactor and style UI

### PR DESCRIPTION
**Pull request by totemc**
lots of TODOs, functionality wip:
* event json -> new event table
* intricacies for deltas
* more ux improvements

### CODE REVIEW

**Comment by mcneiljt** [comment]
Sorry it took me forever to look at this!

I notice the events are loading and checked out the calls that are being made. I think for `/schemas/default` you actually just want `/schemas` I'm not sure about `/deltas/event_type` maybe @adam-zacharski can weigh in.
image

**Comment by mcneiljt** [comment]
It's also possible we should (or someone has in a PR) changed those paths; lmk if that's the case.

**Comment by totemc** [comment]
> Sorry it took me forever to look at this!
> 
> I notice the events are loading and checked out the calls that are being made. I think for `/schemas/default` you actually just want `/schemas` I'm not sure about `/deltas/event_type` maybe @adam-zacharski can weigh in. image

for sure. i couldn't get local set up correctly so my "main" table was `default`. i don't think the route changes were merged while i was working on this, so i'll make sure to update this route to reflect what you've mentioned. i'm also unsure the current state of `deltas/event_type`.

**Comment by mcneiljt** [comment]
Merging this; we didn't have much of anything before so it at least gets us all a start! Thanks @totemc

**Pull request merged**
